"token"="ODg3NjA2MTIzNzgyMzQ0NzA0.YUGlng.nFMvFehNEkaGMoGEQtsl75BjROU"
"bot_id"=887606123782344704
"guild_id"=629187996939190291
"owner_id"=278441913361629195
"dependencies"="discord-py-slash-command pynacl ffmpeg discord lavalink aiodns cchardet toml"
"java_vers"="13.0.1"

[music]
"idle_track"="https://www.youtube.com/watch?v=ioi_-5sAuXQ"
"volume_default"=10
"volume_idle"=4

[lavalink]
"ip"="127.0.0.1"
"port"=2333
"pwd"="P@ssw0RD40*"
"region"="au"
"name"="default-node"

[emojis]
"emotesad"="<:emotesad:872803031274618890>"