"token"="ODg3NjA2MTIzNzgyMzQ0NzA0.YUGlng.nFMvFehNEkaGMoGEQtsl75BjROU"
"bot_id"=887606123782344704
"guild_id"=629187996939190291
"owner_id"=278441913361629195
"java_vers"="11 or 13"

[music]
"queue_page_len"=9
"idle_track"="https://www.youtube.com/watch?v=78cyA-aGaKc"
"volume_default"=10
"volume_idle"=4

[lavalink]
"ip"="127.0.0.1"
"port"=2333
"pwd"="P@ssw0RD40*"
"region"="au"
"name"="default-node"

[emojis]
"emotesad"="<:emotesad:872803031274618890>"