"token"="ODg3NjA2MTIzNzgyMzQ0NzA0.YUGlng.nFMvFehNEkaGMoGEQtsl75BjROU" # the bot's token
"prefix"="!" # Disabled due to slash commands. left in as backup.
"lamz"=629187996939190291

[music]
# Options for the music commands
"max_volume"=100 # Max audio volume. Set to -1 for unlimited.
# "vote_skip"=false # whether vote-skipping is enabled
# "vote_skip_ratio"=0.5 # the minimum ratio of votes needed to skip a song
