[project]
name = "boomer"
version = "0.1.0"
description = "Music bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohappyeyeballs==2.6.2",
    "aiohttp==3.14.1",
    "aiosignal==1.4.0",
    "attrs==26.1.0",
    "audioop-lts==0.2.2",
    "certifi==2026.5.20",
    "cffi==2.0.0",
    "charset-normalizer==3.4.7",
    "colorama==0.4.6",
    "discord-py==2.7.1",
    "dotenv==0.9.9",
    "frozenlist==1.8.0",
    "idna==3.18",
    "lavalink==5.11.0",
    "loguru==0.7.3",
    "multidict==6.7.1",
    "mysql-connector-python==9.7.0",
    "propcache==0.5.2",
    "pycparser==3.0",
    "pynacl==1.6.2",
    "python-dotenv==1.2.2",
    "requests==2.34.2",
    "stringprogressbar==1.1.1",
    "urllib3==2.7.0",
    "win32-setctime==1.2.0",
    "yarl==1.24.2",
]
