'name of saved queue' = [
    'list of youtube URLs',
    'list of youtube URLs',
    'list of youtube URLs',
    'list of youtube URLs',
    'list of youtube URLs',
]

'second saved queue' = [
    'list of youtube URLs',
    'list of youtube URLs',
    'list of youtube URLs',
    'list of youtube URLs',
    'list of youtube URLs',
]

# etc...